package main

import "fmt"

// go build -gcflags='-m' main.go
//
// # command-line-arguments
//./main.go:7:13: inlining call to fmt.Println
//./main.go:7:13: x escapes to heap
//./main.go:7:13: []interface {} literal does not escape
//<autogenerated>:1: .this does not escape
//
// fmt.Println 函数接收的是interface类型
func main() {
	x := 1
	fmt.Println(x)
}

