package main

import "fmt"

func newFn() func() int {
	n := 1
	return func() int {
		return n
	}
}

// # command-line-arguments
//./main.go:7:9: can inline newFn.func1
//./main.go:14:13: inlining call to fmt.Println
//./main.go:7:9: func literal escapes to heap
//./main.go:14:16: fn() escapes to heap
//./main.go:14:13: []interface {} literal does not escape
//<autogenerated>:1: .this does not escape
func main() {
	fn := newFn()
	fmt.Println(fn())
}
